config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.3
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar-ui:
      branch: master
      repo: https://github.com/grycap/oscar-ui
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-thistle-reindeer.sh
        container: qc.acc_geeky-malachite-maltese
  QC.Doc:
    repos:
      github.com/grycap/oscar-ui find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-puce-uakari.sh
        container: qc.doc_bluesy-silver-bison
      github.com/grycap/oscar-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-fuchsia-bobcat.sh
        container: qc.doc_lovely-grey-earwig
      github.com/grycap/oscar-ui markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-sangria-indri.sh
        container: qc.doc_randy-amethyst-eel
  QC.Lic:
    repos:
      github.com/grycap/oscar-ui licensee:
        commands:
        - /usr/bin/env sh .sqa/script.messy-brass-gar.sh
        container: qc.lic_sleazy-brown-wolf
  QC.Sec:
    repos:
      github.com/grycap/oscar-ui bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-pink-antelope.sh
        container: qc.sec_stuffy-lemon-kiwi
  QC.Sty:
    repos:
      github.com/grycap/oscar-ui flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-orange-monkey.sh
        container: qc.sty_silly-brown-kangaroo
      github.com/grycap/oscar-ui hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-fuchsia-lizard.sh
        container: qc.sty_blurry-orchid-bison
      github.com/grycap/oscar-ui jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-amaranth-bee.sh
        container: qc.sty_gloppy-coral-cat
  QC.Ver:
    repos:
      github.com/grycap/oscar-ui get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-chocolate-sloth.sh
        container: qc.ver_bluesy-dandelion-neanderthal
timeout: 1800
