config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.3
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar-ui:
      branch: master
      repo: https://github.com/grycap/oscar-ui
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-green-moorhen.sh
        container: qc.acc_goopy-brown-chamois
  QC.Doc:
    repos:
      github.com/grycap/oscar-ui find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-grey-weasel.sh
        container: qc.doc_craggy-ecru-turkey
      github.com/grycap/oscar-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-magenta-dormouse.sh
        container: qc.doc_stealthy-cyan-dalmatian
      github.com/grycap/oscar-ui markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-cerise-sponge.sh
        container: qc.doc_sickly-viridian-akbash
  QC.Lic:
    repos:
      github.com/grycap/oscar-ui licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-magenta-moose.sh
        container: qc.lic_hilly-burgundy-falcon
  QC.Sty:
    repos:
      github.com/grycap/oscar-ui eslint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-fuchsia-rhinoceros.sh
        container: qc.sty_skinny-aquamarine-albatross
      github.com/grycap/oscar-ui jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-carmine-goat.sh
        container: qc.sty_bumpy-lavender-dogfish
  QC.Ver:
    repos:
      github.com/grycap/oscar-ui get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-amber-slug.sh
        container: qc.ver_flimsy-purple-snake
timeout: 1800
