config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.3
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar-ui:
      branch: master
      repo: https://github.com/grycap/oscar-ui
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-smalt-moth.sh
        container: qc.acc_baggy-sangria-macaw
  QC.Doc:
    repos:
      github.com/grycap/oscar-ui find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-ruby-caracal.sh
        container: qc.doc_seedy-amber-wolverine
      github.com/grycap/oscar-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-sepia-elephant.sh
        container: qc.doc_skinny-blue-scorpion
      github.com/grycap/oscar-ui markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-harlequin-nightingale.sh
        container: qc.doc_stuffy-sapphire-badger
  QC.Lic:
    repos:
      github.com/grycap/oscar-ui licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-emerald-bracke.sh
        container: qc.lic_nerdy-flax-bee
  QC.Sec:
    repos:
      github.com/grycap/oscar-ui bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-pumpkin-tortoise.sh
        container: qc.sec_zippy-cinnabar-cattle
  QC.Sty:
    repos:
      github.com/grycap/oscar-ui flake8:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-asparagus-quetzal.sh
        container: qc.sty_silly-lavender-cheetah
      github.com/grycap/oscar-ui hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-tangerine-lionfish.sh
        container: qc.sty_geeky-blue-dog
      github.com/grycap/oscar-ui jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-teal-coral.sh
        container: qc.sty_sleazy-goldenrod-leopard
  QC.Ver:
    repos:
      github.com/grycap/oscar-ui get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-red-binturong.sh
        container: qc.ver_frumpy-taupe-spoonbill
timeout: 1800
