config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.3
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar-ui:
      branch: master
      repo: https://github.com/grycap/oscar-ui
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-goldenrod-hare.sh
        container: qc.acc_wheezy-sangria-penguin
  QC.Doc:
    repos:
      github.com/grycap/oscar-ui find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-pumpkin-javanese.sh
        container: qc.doc_shaky-saffron-dunker
      github.com/grycap/oscar-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-olive-dugong.sh
        container: qc.doc_cloudy-russet-zebu
      github.com/grycap/oscar-ui markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-brass-raccoon.sh
        container: qc.doc_lousy-sepia-dog
  QC.Lic:
    repos:
      github.com/grycap/oscar-ui licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-taupe-bat.sh
        container: qc.lic_skinny-fuchsia-sheep
  QC.Sty:
    repos:
      github.com/grycap/oscar-ui jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-wheat-buzzard.sh
        container: qc.sty_boozy-silver-capybara
  QC.Ver:
    repos:
      github.com/grycap/oscar-ui get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-jade-capuchin.sh
        container: qc.ver_dorky-alizarin-starfish
timeout: 1800
