config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.3
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar-ui:
      branch: master
      repo: https://github.com/grycap/oscar-ui
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-bistre-buzzard.sh
        container: qc.acc_cranky-orchid-turtle
  QC.Doc:
    repos:
      github.com/grycap/oscar-ui find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-brown-uguisu.sh
        container: qc.doc_slaphappy-crimson-centipede
      github.com/grycap/oscar-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-cream-spitz.sh
        container: qc.doc_greasy-rose-sparrow
      github.com/grycap/oscar-ui markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-red-avocet.sh
        container: qc.doc_snazzy-ultramarine-ragdoll
  QC.Lic:
    repos:
      github.com/grycap/oscar-ui licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-gamboge-centipede.sh
        container: qc.lic_boozy-pear-caterpillar
  QC.Sty:
    repos:
      github.com/grycap/oscar-ui eslint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-auburn-liger.sh
        container: qc.sty_geeky-brown-squid
      github.com/grycap/oscar-ui jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-grey-dormouse.sh
        container: qc.sty_squeaky-rose-spitz
  QC.Ver:
    repos:
      github.com/grycap/oscar-ui get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-sapphire-kingfisher.sh
        container: qc.ver_boozy-linen-chin
timeout: 1800
