config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.3
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar-ui:
      branch: master
      repo: https://github.com/grycap/oscar-ui
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-sangria-coyote.sh
        container: qc.acc_stealthy-maroon-booby
  QC.Doc:
    repos:
      github.com/grycap/oscar-ui find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-ruby-snail.sh
        container: qc.doc_sleazy-lilac-badger
      github.com/grycap/oscar-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-salmon-tzu.sh
        container: qc.doc_grumpy-cinnabar-squirrel
      github.com/grycap/oscar-ui markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-black-gopher.sh
        container: qc.doc_woolly-plum-leopard
  QC.Lic:
    repos:
      github.com/grycap/oscar-ui licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-dandelion-coyote.sh
        container: qc.lic_clammy-viridian-guppy
  QC.Sty:
    repos:
      github.com/grycap/oscar-ui eslint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-sangria-argentino.sh
        container: qc.sty_dorky-brass-kakapo
      github.com/grycap/oscar-ui jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-turquoise-penguin.sh
        container: qc.sty_chummy-green-eagle
  QC.Ver:
    repos:
      github.com/grycap/oscar-ui get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-eggplant-dane.sh
        container: qc.ver_crabby-violet-tamarin
timeout: 1800
