config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.3
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar-ui:
      branch: master
      repo: https://github.com/grycap/oscar-ui
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-brown-booby.sh
        container: qc.acc_bumpy-gold-whippet
  QC.Doc:
    repos:
      github.com/grycap/oscar-ui find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-silver-oriole.sh
        container: qc.doc_breezy-viridian-zorse
      github.com/grycap/oscar-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-cardinal-fowl.sh
        container: qc.doc_squeaky-zucchini-butterfly
      github.com/grycap/oscar-ui markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-seashell-dolphin.sh
        container: qc.doc_muggy-olivine-capuchin
  QC.Lic:
    repos:
      github.com/grycap/oscar-ui licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-rose-ray.sh
        container: qc.lic_silly-razzmatazz-monster
  QC.Sty:
    repos:
      github.com/grycap/oscar-ui jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-carmine-chimpanzee.sh
        container: qc.sty_fuzzy-purple-russel
  QC.Ver:
    repos:
      github.com/grycap/oscar-ui get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-brass-discus.sh
        container: qc.ver_thirsty-heliotrope-dachshund
timeout: 1800
