config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar-ui:
      branch: master
      repo: https://github.com/grycap/oscar-ui
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-dandelion-rottweiler.sh
        container: qc.acc_baggy-apricot-dog
  QC.Doc:
    repos:
      github.com/grycap/oscar-ui find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-fuchsia-quail.sh
        container: qc.doc_chummy-amaranth-dog
      github.com/grycap/oscar-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-goldenrod-moose.sh
        container: qc.doc_lumpy-ivory-gibbon
      github.com/grycap/oscar-ui markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-brass-budgerigar.sh
        container: qc.doc_craggy-taupe-retriever
  QC.Lic:
    repos:
      github.com/grycap/oscar-ui licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-pink-schnauzer.sh
        container: qc.lic_chewy-ochre-squid
  QC.Sty:
    repos:
      github.com/grycap/oscar-ui jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-persimmon-lynx.sh
        container: qc.sty_gloppy-alizarin-squid
      github.com/grycap/oscar-ui stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-ivory-dugong.sh
        container: qc.sty_lousy-olivine-hummingbird
  QC.Ver:
    repos:
      github.com/grycap/oscar-ui get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-viridian-angora.sh
        container: qc.ver_skinny-tan-barb
timeout: 1800
