config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar-ui:
      branch: !!python/tuple
      - master
      - 362b12d1a52dec3cceccd02624cdbffab2cb5b91
      repo: https://github.com/grycap/oscar-ui
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-beige-wolf.sh
        container: qc.acc_nerdy-platinum-elephant
  QC.Doc:
    repos:
      github.com/grycap/oscar-ui find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-grey-mandrill.sh
        container: qc.doc_stealthy-corn-yak
      github.com/grycap/oscar-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-blue-salamander.sh
        container: qc.doc_shabby-sangria-harrier
      github.com/grycap/oscar-ui markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-smalt-ostrich.sh
        container: qc.doc_dorky-champagne-audemer
  QC.Lic:
    repos:
      github.com/grycap/oscar-ui licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-tangerine-tortoise.sh
        container: qc.lic_squeaky-magnolia-audemer
  QC.Sty:
    repos:
      github.com/grycap/oscar-ui jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-firebrick-chameleon.sh
        container: qc.sty_silly-peach-dodo
      github.com/grycap/oscar-ui stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-lavender-tortoise.sh
        container: qc.sty_fuzzy-heliotrope-akbash
  QC.Ver:
    repos:
      github.com/grycap/oscar-ui get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-yellow-bobcat.sh
        container: qc.ver_skanky-violet-flamingo
timeout: 5400
