config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar-ui:
      branch: master
      repo: https://github.com/grycap/oscar-ui
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-purple-anteater.sh
        container: qc.acc_greasy-apricot-cheetah
  QC.Doc:
    repos:
      github.com/grycap/oscar-ui find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-cyan-birman.sh
        container: qc.doc_messy-ultramarine-tapir
      github.com/grycap/oscar-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-rose-buzzard.sh
        container: qc.doc_pretty-razzmatazz-zorse
      github.com/grycap/oscar-ui markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-cinnabar-retriever.sh
        container: qc.doc_gloppy-grey-hummingbird
  QC.Lic:
    repos:
      github.com/grycap/oscar-ui licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ready-chocolate-flamingo.sh
        container: qc.lic_grumpy-amethyst-fossa
  QC.Ver:
    repos:
      github.com/grycap/oscar-ui get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-chartreuse-fly.sh
        container: qc.ver_hazy-cinnamon-ostrich
timeout: 1800
